version: '3.3'

networks:
  test:
    driver: bridge
    ipam:
      config:
        - subnet: 174.18.0.1/16

services:
  db:
    image: postgres   
    # volumes:
    #   - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: FiGreo32reoqowR1321e12
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      test:
        ipv4_address: 174.18.0.4

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      test:
        ipv4_address: 174.18.0.5
  
  redis-master:
    image: 'bitnami/redis:latest'
    ports:
      - 6379:6379
    environment:      
      - REDIS_PASSWORD=FiGreo32reoqowR1321e12
    networks:
      test:
        ipv4_address: 174.18.0.6 

  redis-commander:  
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOST=174.18.0.6
    - REDIS_PORT=6379
    - REDIS_PASSWORD=FiGreo32reoqowR1321e12
    ports:
    - "8081:8081"
    networks:
     test:
       ipv4_address: 174.18.0.7 